[[faq]]
= Frequently Asked Questions
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

== FAQ
This section is to answer frequently asked questions about working with asciibinder.

=== Why Asciibinder
Because we like it

=== Why aren't any of the FAQ answers on here related to my actual question
This site is still very much in its infancy. This FAQ page is meant to serve as an example page as well as a FAQ. If you look at the welcome/faq.adoc file, you will see how to use some of the features of asciibinder.
[IMPORTANT]
====
If I want to write something important, it would look like this.
====

[WARNING]
====
If I want to warn people of impending doom, it would look like this
====

[NOTE]
====
If I want to leave a note, I would use this
====

=== Asciidoc
If there is anything not covered, you can refer to the upstream asciidoc. http://asciidoc.org/

Asciibinder uses asciidoc, so methods available in asciidoc should work in asciibinder.
